spring.application.name=SpringBootFirst

#MongoDB connection URI
#spring.data.mongodb.uri= mongodb+srv://dineshmahendran2002:YCMLn25m6eUFhKe7@cluster0.0ucvs2w.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0;
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.5.2;
spring.data.mongodb.port=27017	
spring.data.mongodb.database=food_delivery
server.port = 8081